# action.yml
name: 'Tableau Workbook Action'
description: 'Github Action to validate and publish your Tableau Workbook'
branding:
  icon: 'bar-chart-2'
  color: 'blue'
inputs:
  workbook_dir:
    description: 'Path to you workbook directory'
    required: true
  env:
    description: 'Target environments'
    required: true
  repo_token:
    description: 'Repo access token'
    required: true
runs:
  using: 'docker'
  steps:
    - run |
      export SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}
      export SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}
      export SNOWFLAKE_HOST=${{ secrets.SNOWFLAKE_HOST }}

  image: 'Dockerfile'
  args:
    - ${{ inputs.workbook_dir}}
    - ${{ inputs.env }}
    - ${{ inputs.repo_token }}
